# Generated by Django 5.0.7 on 2024-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, upload_to='pictures/', verbose_name='Аватар')),
                ('phone_number', models.CharField(blank=True, help_text='Введите номер телефона (необязательно)', max_length=15, verbose_name='Номер телефона')),
                ('country', models.CharField(blank=True, help_text='Введите страну (необязательно)', max_length=30, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
