# Generated by Django 5.0.7 on 2024-07-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Изображение(превью)')),
                ('category', models.CharField(blank=True, max_length=500, null=True, verbose_name='Категория')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена за покупку')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания записи в БД')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения записи в БД')),
                ('сategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
            },
        ),
    ]
