# Generated by Django 5.0.7 on 2024-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_сategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'наименование категории', 'verbose_name_plural': 'наименования категорий'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'наименование продукта', 'verbose_name_plural': 'наименования продуктов'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
