# Generated by Django 5.0.7 on 2025-01-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_manufactured_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение(превью)'),
        ),
    ]
