# Generated by Django 5.0.7 on 2025-02-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'can unpublish product')], 'verbose_name': 'наименование продукта', 'verbose_name_plural': 'наименования продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_publicated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(blank=True, default='False', null=True, verbose_name='Дата производства продукта'),
        ),
    ]
